version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: guest-logix-db
      POSTGRES_USER: gordon
      POSTGRES_PASSWORD: password
    volumes:
      - ./db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - guest-logix-network
    restart: unless-stopped

networks:
  guest-logix-network:
    driver: bridge

volumes:
  postgres-data:
