spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/guest-logix-db
    username: gordon
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true